### ISSUE TITLE
Fetch all schemas in a directory

### ISSUE THREAD

**Issue by int-index** [seagreen/hjsonschema#32]
I have a directory `schemas` that contains hierarchically organized JSON schema files. One of them is `some_model`, but there are others, referenced by it.

In Ruby, validation is quite easy for this:

```
JSON::Validator.validate!("schemas/some_model", json_data)
```

The validator automatically fetches all referenced schemas. Dead simple and just works.

Please, explain how to do so using this library, because I'm lost, looking at types like this one:

```
fetchReferencedSchemas'
  :: forall schema. FromJSON schema
  => (schema -> [schema])
  -> (schema -> Maybe Text)
  -> (schema -> Maybe Text)
  -> (Text -> IO LBS.ByteString)
  -> URISchemaMap schema
  -> SchemaContext schema
  -> IO (SchemaCache schema)
```

I just want to validate some JSON against a schema.

**Comment by seagreen** [comment]
There's a simpler `fetchReferencedSchemas` function specialized for Draft4 and [exported for normal use](https://github.com/seagreen/hjsonschema/blob/master/src/Data/JsonSchema/Draft4.hs#L49). That's the one [used in the example](https://github.com/seagreen/hjsonschema/blob/master/examples/Standard.hs).

It only uses HTTP to fetch schemas though, would starting an HTTP server in your `schemas` directory be an option? After that you could follow the example code exactly.

If that's not an option I can talk you through making your own schema fetcher that uses the filesystem instead of HTTP, or you can wait a couple days and I'll release a simpler `fetchReferencedSchemas'` that isn't such a mess, and also add an alternate version to the library that uses the filesystem instead of HTTP.

**Comment by int-index** [comment]
Thank you for taking a look into this.

> would starting an HTTP server in your schemas directory be an option?

I'm afraid that starting an HTTP server for regression testing is a bit of an overkill.

> or you can wait a couple days

I can wait until you release a new version of the combinator that uses the filesystem. I don't particularly care about performance and a simple combinator like `validate :: FilePath -> JSON -> IO [Failure]` would suit my needs perfectly (it would actually be a drop-in replacement for the Ruby solution).

In fact, if you could show me how to define such a function using the current version of the library, it'd solve my problem too.

**Comment by seagreen** [comment]
I'll push the new version tonight (along with instructions, which will now be thankfully short).

**Comment by int-index** [comment]
Awesome, looking forward to it.

**Comment by seagreen** [comment]
btw do the references in your documents specify `file` as the protocol (eg `file://host/path`) or are they just unadorned filepaths?

**Comment by int-index** [comment]
They look like this:

```
"contact_info": {
      "$ref": "models/contact_info"
    }
```

**Comment by seagreen** [comment]
Mind trying out this function (from the `fetch-improvements` branch): https://github.com/seagreen/hjsonschema/blob/fetch-improvements/src/Data/JsonSchema/Draft4.hs#L53.

I haven't added it to the `examples` yet, but there's a demonstration of how to use it in the tests: https://github.com/seagreen/hjsonschema/blob/fetch-improvements/tests/Local.hs#L101

Let me know how it goes. Improving fetching internals has been on my list of things to do, but I kept putting it off.

**Comment by int-index** [comment]
I can't build this branch because there's a missing dependency:

```
--  Failure when adding dependencies:    
      hjsonpointer: needed (>=0.3 && <0.4), stack configuration has no specified version (latest applicable is 0.3.0.0)
    needed for package hjsonschema-0.9.0.0
```

Looking at https://github.com/seagreen/hjsonpointer I couldn't find any updates since `0.3`. Perhaps you forgot to push?

**Comment by int-index** [comment]
So I've almost got this to work.

Here's my code that calls the library:

```
testSchema :: ToJSON j => Text -> j -> IO ()
testSchema name j = do
  res <- fetchFilesystemAndValidate schemaWithURI (toJSON j)
  case res of
    Left a  -> throwIO (AssertionFailed (show a))
    Right _ -> return ()
  where
    schemaWithURI = SchemaWithURI schema (Just schemaPath)
    schema        = emptySchema { _schemaRef = Just name }
    schemaPath    = "../schemas/"
```

To validate against `../schemas/some_model` I call `testSchema "some_model" mydata`.
To validate against `../schemas/subdir/some_model`, I call `testSchema "subdir/some_model" mydata`.

Schemas that don't contain references validate successfully. The ones that do fail with errors like this:

```
(ReadFailure ../schemas/subdir/some_model1some_model2: openBinaryFile: does not exist (No such file or directory)
```

Here `subdir/some_model1` contains `"$ref": "some_model2"`. Instead of looking for `../schemas/subdir/some_model2` the fetching algorithm looks for `../schemas/subdir/some_model1some_model2`.

**Comment by dredozubov** [comment]
+1 i'd really like to see this fixed, this is a show-stopper

**Comment by seagreen** [comment]
@int-index Wrote a hopeful fix along with some new tests [here](https://github.com/seagreen/hjsonschema/commit/316bf43fcaed98e74aab4d70d94a26074aa87f1a#diff-e7b7a648b3c50b42a875954a185e5408R18) would you be willing to try it out? Thanks again for the bug reports.

**Comment by seagreen** [comment]
@dredozubov My personal use for JSON schema needs neither resolution scope nor relative references, so they haven't gotten the attention they deserve. We'll get the situation improved in the next release.

**Comment by int-index** [comment]
Most of the schemas now fail to validate for reasons different from reference resolution. I will investigate later and open separate issues if necessary.

There's still one failure with regards to reference resolution. If a schema mentions itself via `"$ref": "#"`, the algorithm tries to read its parent directory instead (as a file).

**Comment by seagreen** [comment]
@int-index Your last issue with `"$ref": "#"` should be fixed on the [fetch-improvements branch](https://github.com/seagreen/hjsonschema/tree/fetch-improvements), will you let me know if that worked?

**Comment by int-index** [comment]
@seagreen No, it didn't work. I've set up a repository to reproduce the issue: https://github.com/int-index/hjsonschema-vs-gem

In this repo you will find a file `Spec.hs`. You can replace `testCase = testCaseHaskell` with `testCase = testCaseRuby` to see that validation actually works with Ruby but fails with Haskell.

I hope it will make it easier for you to debug the issue. I also added you as a collaborator so you can change the code there.

The repo currently contains only one failing test case (the one with `"ref": "#"`) but I will be adding more.

**Comment by seagreen** [comment]
@int-index Really nice work. It also means we now have more tests for [this issue](https://github.com/seagreen/hjsonschema/issues/17), because even if the reference fetching works correctly hjsonschema doesn't handle "pattern" right, and it shows up after a few test cases. The first step is for me to get fetching fixed though..

**Comment by int-index** [comment]
This issue seems to be finally fixed! Thank you. I still have some test suite failures that I will report as a separate issue.

**Comment by seagreen** [comment]
You're welcome. Thanks for your fantastic work putting together hjsonschema-vs-gem.

**Comment by dredozubov** [comment]
Thanks to all, hope to see the new release on hackage soon!
